"""Render PR lists as GitHub-flavored Markdown, grouped by squad.

This is the "always-current" rendering: writes into a fixed GitHub issue body
that the weekly Slack ping links to. Permanent URL, refreshes in place.
"""
from datetime import datetime, timezone

from pr_digest.slack_formatter import SquadSection, age_badge, size_label


def _format_pr_line(pr: dict) -> str:
    title = pr["title"]
    if len(title) > 90:
        title = title[:87] + "..."

    badges = []
    if pr["lgtm"] and not pr["approved"]:
        badges.append("🟢 LGTM")
    elif pr.get("community_lgtm") and not pr["approved"]:
        badges.append("🟢 LGTM (comment)")
    badges.append(age_badge(pr["age_days"]))
    if pr.get("community_assignee"):
        badges.append(f"👀 reviewing: `{pr['community_assignee']}`")

    badge_str = " · ".join(badges)
    # Append `/files` to the PR URL: GitHub's cross-reference detector matches
    # bare `/pull/N` URLs, so appending a subpath breaks the pattern while
    # still navigating to the same PR (Files changed tab). Stops the bot from
    # leaving "mentioned this PR" events on upstream kserve PRs.
    # Also: wrapping the whole `#N title` in the link prevents the `#N`
    # autolinker from cross-referencing to the wrong repo.
    return (
        f"- **[#{pr['number']} {title}]({pr['url']}/files)** · "
        f"{size_label(pr)} · "
        f"by `{pr['author']}` · {badge_str}"
    )


def _bucket_section(heading: str, prs: list[dict]) -> list[str]:
    if not prs:
        return []
    lines = ["", f"### {heading}", ""]
    lines.extend(_format_pr_line(p) for p in prs)
    return lines


def _squad_section(
    name: str, ready: list[dict], fast: list[dict], deep: list[dict]
) -> list[str]:
    lines = [
        "",
        f"## 🧩 {name}",
        f"_{len(ready)} ready · {len(fast)} fast · {len(deep)} deep_",
    ]
    if not (ready or fast or deep):
        lines.extend(["", "_🎉 nothing open_"])
        return lines
    lines.extend(_bucket_section(
        "🟢 Ready for approver stamp _(LGTM'd, awaiting `/approve`, any size)_",
        ready,
    ))
    lines.extend(_bucket_section("Fast lane _(small PRs awaiting LGTM)_", fast))
    lines.extend(_bucket_section("Deep review _(larger PRs awaiting LGTM)_", deep))
    return lines


def _community_section(
    ready: list[dict], fast: list[dict], deep: list[dict]
) -> list[str]:
    """Top-of-digest Community PRs section: cross-team PRs the team is engaged
    in (external author, with at least one team participant). Same bucket
    structure as a squad section so the mental model is parallel."""
    lines = [
        "",
        "## 🤝 Community PRs we're helping land",
        f"_{len(ready)} ready · {len(fast)} fast · {len(deep)} deep · "
        "team member assigned or reviewing, external author_",
    ]
    lines.extend(_bucket_section(
        "🟢 Ready for approver stamp _(LGTM'd, awaiting `/approve`, any size)_",
        ready,
    ))
    lines.extend(_bucket_section("Fast lane _(small PRs awaiting LGTM)_", fast))
    lines.extend(_bucket_section("Deep review _(larger PRs awaiting LGTM)_", deep))
    return lines


def build_digest_markdown(
    community_buckets: tuple[list[dict], list[dict], list[dict]],
    squad_sections: list[SquadSection],
) -> str:
    cr, cf, cd = community_buckets
    sr = sum(len(r) for _, r, _, _ in squad_sections)
    sf = sum(len(f) for _, _, f, _ in squad_sections)
    sd = sum(len(d) for _, _, _, d in squad_sections)
    t_ready = len(cr) + sr
    t_fast = len(cf) + sf
    t_deep = len(cd) + sd
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# 📋 Upstream PR Digest",
        "",
        (
            f"_Updated {now} · {t_ready} ready · {t_fast} fast · "
            f"{t_deep} deep · grouped by squad, oldest first._"
        ),
        "",
        "---",
    ]

    if t_ready + t_fast + t_deep == 0:
        lines.extend(["", "🎉 No open upstream PRs from the team. Nice."])
    else:
        if len(cr) + len(cf) + len(cd):
            lines.extend(_community_section(cr, cf, cd))
        for name, ready, fast, deep in squad_sections:
            lines.extend(_squad_section(name, ready, fast, deep))

    lines.extend([
        "",
        "---",
        "",
        "_Auto-generated by team-tooling. Refreshes on a schedule; the weekly "
        "Slack ping links here._",
    ])

    return "\n".join(lines)
