"""Render PR lists as GitHub-flavored Markdown, grouped by squad.

This is the "always-current" rendering: writes into a fixed GitHub issue body
that the weekly Slack ping links to. Permanent URL, refreshes in place.
"""
from datetime import datetime, timezone

from pr_digest.slack_formatter import SquadSection, age_badge, size_label


def _format_pr_line(pr: dict) -> str:
    title = pr["title"]
    if len(title) > 90:
        title = title[:87] + "..."

    badges = []
    if pr["lgtm"] and not pr["approved"]:
        badges.append("🟢 LGTM")
    elif pr.get("community_lgtm") and not pr["approved"]:
        badges.append("🟢 LGTM (comment)")
    badges.append(age_badge(pr["age_days"]))

    badge_str = " · ".join(badges)
    # Wrap the whole title+number in the link so GitHub's auto-linker doesn't
    # cross-reference `#N` to the wrong repo.
    return (
        f"- **[#{pr['number']} {title}]({pr['url']})** · "
        f"{size_label(pr)} · "
        f"by `{pr['author']}` · {badge_str}"
    )


def _bucket_section(heading: str, prs: list[dict]) -> list[str]:
    if not prs:
        return []
    lines = ["", f"### {heading}", ""]
    lines.extend(_format_pr_line(p) for p in prs)
    return lines


def _squad_section(
    name: str, ready: list[dict], fast: list[dict], deep: list[dict]
) -> list[str]:
    lines = [
        "",
        f"## 🧩 {name}",
        f"_{len(ready)} ready · {len(fast)} fast · {len(deep)} deep_",
    ]
    if not (ready or fast or deep):
        lines.extend(["", "_🎉 nothing open_"])
        return lines
    lines.extend(_bucket_section(
        "🟢 Ready for approver stamp _(LGTM'd, awaiting `/approve`, any size)_",
        ready,
    ))
    lines.extend(_bucket_section("Fast lane _(small PRs awaiting LGTM)_", fast))
    lines.extend(_bucket_section("Deep review _(larger PRs awaiting LGTM)_", deep))
    return lines


def build_digest_markdown(sections: list[SquadSection]) -> str:
    t_ready = sum(len(r) for _, r, _, _ in sections)
    t_fast = sum(len(f) for _, _, f, _ in sections)
    t_deep = sum(len(d) for _, _, _, d in sections)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# 📋 Upstream PR Digest",
        "",
        (
            f"_Updated {now} · {t_ready} ready · {t_fast} fast · "
            f"{t_deep} deep · grouped by squad, oldest first._"
        ),
        "",
        "---",
    ]

    if t_ready + t_fast + t_deep == 0:
        lines.extend(["", "🎉 No open upstream PRs from the team. Nice."])
    else:
        for name, ready, fast, deep in sections:
            lines.extend(_squad_section(name, ready, fast, deep))

    lines.extend([
        "",
        "---",
        "",
        "_Auto-generated by team-tooling. Refreshes on a schedule; the weekly "
        "Slack ping links here._",
    ])

    return "\n".join(lines)
